[target.wasm32-unknown-unknown]
runner = "wasm-bindgen-test-runner"
rustflags = "--cfg=web_sys_unstable_apis --cfg=getrandom_backend=\"wasm_js\""

[build]
target = "wasm32-unknown-unknown"

[env]
RUSTFLAGS = "--cfg getrandom_backend=\"wasm_js\""
